org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# This builtInKotlin flag was added automatically by Flutter migrator
android.newDsl=false
android.builtInKotlin=false

# Enable parallel execution (GitHub ubuntu-latest = 4 vCPU)
org.gradle.parallel=true
org.gradle.workers.max=4
